name: "YouTube Audio Clipper"
version: "1.0.0"
slug: "youtube_audio_clipper"
description: "Download and clip YouTube audio"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
type: application
startup: application
boot: auto
ports:
  8080/tcp: 8080
ports_description:
  8080/tcp: "Web interface"
webui: "http://[HOST]:[PORT:8080]"
map:
  - downloads:"rw" 
