name: "YouTube Audio Clipper"
version: "1.0.0"
slug: "youtube_audio_clipper"
path: "youtube_audio_clipper"
description: "Download and clip YouTube audio"
init: false
url: "https://github.com/DaanyaalSobani/Youtube-Audio-Clipper"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: services
boot: auto
ports:
  8080/tcp: null
ports_description:
  8080/tcp: "Web interface"
type: application
ingress: true  # Enable ingress support - allows access through HA interface
ingress_port: 8080  # The port your app listens on inside the container